### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_http_api#220]
The following tests currently fail and need to be tweaked according to iRODS 4.3.1 behavior.

```
======================================================================
FAIL: test_copy_operation_returns_an_error_when_destination_path_is_a_collection (__main__.test_data_objects_endpoint)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_irods_http_api.py", line 1054, in test_copy_operation_returns_an_error_when_destination_path_is_a_collection
    self.assertEqual(r.json()['irods_response']['status_code'], irods_error_codes.CAT_NO_ACCESS_PERMISSION)
AssertionError: -312000 != -818000

======================================================================
FAIL: test_registering_a_new_data_object (__main__.test_data_objects_endpoint)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_irods_http_api.py", line 1250, in test_registering_a_new_data_object
    self.assertEqual(r.json()['irods_response']['status_code'], 0)
AssertionError: -516002 != 0

======================================================================
FAIL: test_registering_an_additional_replica_for_an_existing_data_object (__main__.test_data_objects_endpoint)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_irods_http_api.py", line 1328, in test_registering_an_additional_replica_for_an_existing_data_object
    self.assertEqual(r.json()['irods_response']['status_code'], 0)
AssertionError: -516002 != 0
```

**Comment by korydraughn** [comment]
The registration tests fail when the file being registered isn't on the same computer as the the iRODS server. This is expected. And the failures being reported are due to the iRODS server being in a container while the test suite is run on the host computer.

To resolve the registration tests, we'll include the data size in the request to keep the server from attempting to stat the file.

`test_copy_operation_returns_an_error_when_destination_path_is_a_collection` fails because the test is written for a post 4.3.1 iRODS server. The test needs to be updated to match the behavior of an iRODS 4.3.1 server.
