### ISSUE TITLE
Reading binary data using curl without --output option results in the HTTP API server crashing

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_http_api#332]
## Bug Report

I was able to crash the HTTP API by attempting to read a 96000000 byte binary file from iRODS using curl.

Here's the command along with the output.
```bash
$ curl -H "Authorization: Bearer $bearer_token" "$base_url/data-objects" --data-urlencode 'op=read' --data-urlencode 'lpath=/tempZone/home/kory/foo' -vG                   
*   Trying 127.0.0.1:9000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9000 (#0)
> GET /irods-http-api/0.4.0/data-objects?op=read&lpath=%2FtempZone%2Fhome%2Fkory%2Ffoo HTTP/1.1
> Host: localhost:9000
> User-Agent: curl/7.68.0
> Accept: */*
> Authorization: Bearer 283d0c8c-0e92-4825-a8fb-95409d23973d
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: irods_http_api/0.4.0 (0e0fd03368857009404799fab4eab86d5d6a396b)
< Content-Type: application/octet-stream
< Transfer-Encoding: chunked
< 
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
* Failed writing body (0 != 8192)
* Failed reading the chunked-encoded stream
* Closing connection 0
```

And here's the output of the HTTP API.
```
[2024-09-13 18:32:33.194] [P:2953427] [trace] [T:2953464] get_connection: Changing identity associated with connection to [kory].
[2024-09-13 18:32:33.194] [P:2953427] [trace] [T:2953464] get_connection: Successfully changed identity associated with connection to [kory].
[2024-09-13 18:32:33.226] [P:2953427] [trace] [T:2953464] [127.0.0.1] op_read: 4.2 compatibility disabled. Internal buffer size exceeded. Using dedicated iRODS connection.
[2024-09-13 18:32:33.226] [P:2953427] [trace] [T:2953464] [127.0.0.1] op_read: Connecting to iRODS server as [kory].
[2024-09-13 18:32:33.411] [P:2953427] [trace] [T:2953464] [127.0.0.1] op_read: Opening stream for reading to data object [/tempZone/home/kory/foo].
[2024-09-13 18:32:33.458] [P:2953427] [trace] [T:2953464] [127.0.0.1] op_read: Seeking to offset [0] in data object [/tempZone/home/kory/foo].
[2024-09-13 18:32:33.458] [P:2953427] [trace] [T:2953464] [127.0.0.1] start: Posting task for asynchronously writing headers.
[2024-09-13 18:32:33.458] [P:2953427] [trace] [T:2953474] [127.0.0.1] start: Wrote [160] bytes representing headers.
[2024-09-13 18:32:33.463] [P:2953427] [debug] [T:2953465] [127.0.0.1] stream_bytes_to_client: Read [8192] bytes from data object.
[2024-09-13 18:32:33.464] [P:2953427] [debug] [T:2953471] [127.0.0.1] stream_bytes_to_client: Wrote [8200] bytes to socket.
[2024-09-13 18:32:33.466] [P:2953427] [debug] [T:2953466] [127.0.0.1] stream_bytes_to_client: Read [8192] bytes from data object.
terminate called after throwing an instance of 'boost::wrapexcept<boost::system::system_error>'
  what():  remote_endpoint: Transport endpoint is not connected [system:107 at /opt/irods-externals/boost1.81.0-1/include/boost/asio/detail/reactive_socket_service.hpp:218:35 in function 'remote_endpoint']
Aborted (core dumped)
```

If I pass `--output ./foo.bin`, then everything works.

Given that this results in a core dump, we should be able to track down the cause of the crash.

**Comment by korydraughn** [comment]
This is caused by curl closing the socket unexpectedly and the HTTP API attempting to access an already closed socket.

```
Thread 1 "irods_http_api" hit Breakpoint 1, irods::http::session::ip[abi:cxx11]() const (this=0x7fffbc001740) at /mnt/hdd_3tb/github/irods_client_http_api/core/src/session.cpp:43
43                      return stream_.socket().remote_endpoint().address().to_string();
(gdb) bt
#0  irods::http::session::ip[abi:cxx11]() const (this=0x7fffbc001740) at /mnt/hdd_3tb/github/irods_client_http_api/core/src/session.cpp:43
#1  0x00005555560e44fa in irods::http::log::debug<char const*&, unsigned long&> (_sp=..., _format=..., _args=@0x7fffffffc168: 8200, _args=@0x7fffffffc168: 8200) at /mnt/hdd_3tb/github/irods_client_http_api/core/include/irods/private/http_api/log.hpp:65
#2  0x0000555556092945 in (anonymous namespace)::incremental_read::stream_bytes_to_client()::{lambda()#1}::operator()()::{lambda(auto:1 const&, unsigned long)#1}::operator()<boost::system::error_code>(boost::system::error_code const&, unsigned long) (this=0x7fffffffc650, _ec=..., _bytes_transferred=8200)
    at /mnt/hdd_3tb/github/irods_client_http_api/endpoints/data_objects/src/main.cpp:368
#3  0x0000555556072dc6 in boost::beast::async_base<(anonymous namespace)::incremental_read::stream_bytes_to_client()::{lambda()#1}::operator()()::{lambda(auto:1 const&, unsigned long)#1}, boost::asio::any_io_executor, std::allocator<void> >::complete_now<boost::system::error_code&, unsigned long&>(boost::system::error_code&, unsigned long&) (this=0x7fffffffc648, 
    args=@0x7fffffffc6c0: 8200, args=@0x7fffffffc6c0: 8200) at /opt/irods-externals/boost1.81.0-2/include/boost/beast/core/async_base.hpp:426
#4  0x0000555556072b43 in boost::beast::http::detail::write_op<(anonymous namespace)::incremental_read::stream_bytes_to_client()::{lambda()#1}::operator()()::{lambda(auto:1 const&, unsigned long)#1}, boost::beast::basic_stream<boost::asio::ip::tcp, boost::asio::any_io_executor, boost::beast::unlimited_rate_policy>, boost::beast::http::detail::serializer_is_done, false, boost::beast::http::buffer_body, boost::beast::http::basic_fields<std::allocator<char> > >::operator()(boost::system::error_code, unsigned long) (this=0x7fffffffc648, ec=..., bytes_transferred=8200) at /opt/irods-externals/boost1.81.0-2/include/boost/beast/http/impl/write.hpp:248
#5  0x00005555560780ed in boost::beast::async_base<boost::beast::http::detail::write_op<(anonymous namespace)::incremental_read::stream_bytes_to_client()::{lambda()#1}::operator()()::{lambda(auto:1 const&, unsigned long)#1}, boost::beast::basic_stream<boost::asio::ip::tcp, boost::asio::any_io_executor, boost::beast::unlimited_rate_policy>, boost::beast::http::detail::serializer_is_done, false, boost::beast::http::buffer_body, boost::beast::http::basic_fields<std::allocator<char> > >, boost::asio::any_io_executor, std::allocator<void> >::complete_now<boost::system::error_code&, unsigned long&>(boost::system::error_code&, unsigned long&) (this=0x7fffffffc640, args=@0x7fffffffc2f0: 8200, args=@0x7fffffffc2f0: 8200)
    at /opt/irods-externals/boost1.81.0-2/include/boost/beast/core/async_base.hpp:426
#6  0x0000555556076f25 in boost::beast::http::detail::write_some_op<boost::beast::http::detail::write_op<(anonymous namespace)::incremental_read::stream_bytes_to_client()::{lambda()#1}::operator()()::{lambda(auto:1 const&, unsigned long)#1}, boost::beast::basic_stream<boost::asio::ip::tcp, boost::asio::any_io_executor, boost::beast::unlimited_rate_policy>, boost::beast::http::detail::serializer_is_done, false, boost::beast::http::buffer_body, boost::beast::http::basic_fields<std::allocator<char> > >, boost::beast::basic_stream<boost::asio::ip::tcp, boost::asio::any_io_executor, boost::beast::unlimited_rate_policy>, false, boost::beast::http::buffer_body, boost::beast::http::basic_fields<std::allocator<char> > >::operator()(boost::system::error_code, unsigned long) (this=0x7fffffffc640, ec=..., bytes_transferred=8200) at /opt/irods-externals/boost1.81.0-2/include/boost/beast/http/impl/write.hpp:136
#7  0x00005555560782dd in boost::beast::async_base<boost::beast::http::detail::write_some_op<boost::beast::http::detail::write_op<(anonymous namespace)::incremental_read::stream_bytes_to_client()::{lambda()#1}::operator()()::{lambda(auto:1 const&, unsigned long)#1}, boost::beast::basic_stream<boost::asio::ip::tcp, boost::asio::any_io_executor, boost::beast::unlimited_rate_policy>, boost::beast::http::detail::serializer_is_done, false, boost::beast::http::buffer_body, boost::beast::http::basic_fields<std::allocator<char> > >, boost::beast::basic_stream<boost::asio::ip::tcp, boost::asio::any_io_executor, boost::beast::unlimited_rate_policy>, false, boost::beast::http::buffer_body, boost::beast::http::basic_fields<std::allocator<char> > >, boost::asio::any_io_executor, std::allocator<void> >::complete_now<boost::system::error_code&, unsigned long&>(boost::system::error_code&, unsigned long&) (this=0x7fffffffc638, args=@0x7fffffffc590: 8200, args=@0x7fffffffc590: 8200) at /opt/irods-externals/boost1.81.0-2/include/boost/beast/core/async_base.hpp:426
#8  0x00005555560854e9 in boost::beast::basic_stream<boost::asio::ip::tcp, boost::asio::any_io_executor, boost::beast::unlimited_rate_policy>::ops::transfer_op<false, boost::beast::detail::buffers_ref<boost::beast::buffers_prefix_view<boost::beast::buffers_suffix<boost::beast::buffers_cat_view<boost::beast::http::detail::chunk_size, boost::asio::const_buffer, boost::beast::http::chunk_crlf, boost::asio::const_buffer, boost::beast::http::chunk_crlf> > const&> >, boost::beast::http::detail::write_some_op<boost::beast::http::detail::write_op<(anonymous namespace)::incremental_read::stream_bytes_to_client()::{lambda()#1}::operator()()::{lambda(auto:1 const&, unsigned long)#1}, boost::beast::basic_stream<boost::asio::ip::tcp, boost::asio::any_io_executor, boost::beast::unlimited_rate_policy>, boost::beast::http::detail::serializer_is_done, false, boost::beast::http::buffer_body, boost::beast::http::basic_fields<std::allocator<char> > >, boost::beast::basic_stream<boost::asio::ip::tcp, boost::asio::any_io_executor, boost::beast::unlimited_rate_policy>, false, boost::beast::http::buffer_body, boost::beast::http::basic_fields<std::allocator<char> > > >::operator()(boost::system::error_code, unsigned long) (this=0x7fffffffc638, ec=..., bytes_transferred=8200) at /opt/irods-externals/boost1.81.0-2/include/boost/beast/core/impl/basic_stream.hpp:425
#9  0x00005555560863aa in boost::asio::detail::binder2<boost::beast::basic_stream<boost::asio::ip::tcp, boost::asio::any_io_executor, boost::beast::unlimited_rate_policy>::ops::transfer_op<false, boost::beast::detail::buffers_ref<boost::beast::buffers_prefix_view<boost::beast::buffers_suffix<boost::beast::buffers_cat_view<boost::beast::http::detail::chunk_size, boost::asio::const_buffer, boost::beast::http::chunk_crlf, boost::asio::const_buffer, boost::beast::http::chunk_crlf> > const&> >, boost::beast::http::detail::write_some_op<boost::beast::http::detail::write_op<(anonymous namespace)::incremental_read::stream_bytes_to_client()::{lambda()#1}::operator()()::{lambda(auto:1 const&, unsigned long)#1}, boost::beast::basic_stream<boost::asio::ip::tcp, boost::asio::any_io_executor, boost::beast::unlimited_rate_policy>, boost::beast::http::detail::serializer_is_done, false, boost::beast::http::buffer_body, boost::beast::http::basic_fields<std::allocator<char> > >, boost::beast::basic_stream<boost::asio::ip::tcp, boost::asio::any_io_executor, boost::beast::unlimited_rate_policy>, false, boost::beast::http::buffer_body, boost::beast::http::basic_fields<std::allocator<char> > > >, boost::system::error_code, unsigned long>::operator()() (this=0x7fffffffc638) at /opt/irods-externals/boost1.81.0-2/include/boost/asio/detail/bind_handler.hpp:289
#10 0x0000555556086a59 in boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::binder2<boost::beast::basic_stream<boost::asio::ip::tcp, boost::asio::any_io_executor, boost::beast::unlimited_rate_policy>::ops::transfer_op<false, boost::beast::detail::buffers_ref<boost::beast::buffers_prefix_view<boost::beast::buffers_suffix<boost::beast::buffers_cat_view<boost::beast::http::detail::chunk_size, boost::asio::const_buffer, boost::beast::http::chunk_crlf, boost::asio::const_buffer, boost::beast::http::chunk_crlf> > const&> >, boost::beast::http::detail::write_some_op<boost::beast::http::detail::write_op<(anonymous namespace)::incremental_read::stream_bytes_to_client()::{lambda()#1}::operator()()::{lambda(auto:1 const&, unsigned long)#1}, boost::beast::basic_stream<boost::asio::ip::tcp, boost::asio::any_io_executor, boost::beast::unlimited_rate_policy>, boost::beast::http::detail::serializer_is_done, false, boost::beast::http::buffer_body, boost::beast::http::basic_fields<std::allocator<char> > >, boost::beast::basic_stream<boost::asio::ip::tcp, boost::asio::any_io_executor, boost::beast::unlimited_rate_policy>, false, boost::beast::http::buffer_body, boost::beast::http::basic_fields<std::allocator<char> > > >, boost::system::error_code, unsigned long>, boost::asio::detail::binder2<boost::beast::basic_stream<boost::asio::ip::tcp, boost::asio::any_io_executor, boost::beast::unlimited_rate_policy>::ops::transfer_op<false, boost::beast::detail::buffers_ref<boost::beast::buffers_prefix_view<boost::beast::buffers_suffix<boost::beast::buffers_cat_view<boost::beast::http::detail::chunk_size, boost::asio::const_buffer, boost::beast::http::chunk_crlf, boost::asio::const_buffer, boost::beast::http::chunk_crlf> > const&> >, boost::beast::http::detail::write_some_op<boost::beast::http::detail::write_op<(anonymous namespace)::incremental_read::stream_bytes_to_client()::{lambda()#1}::operator()()::{lambda(auto:1 const&, unsigned long)#1}, boost::beast::basic_stream<boost::asio::ip::tcp, boost::asio::any_io_executor, boost::beast::unlimited_rate_policy>, boost::beast::http::detail::serializer_is_done, false, boost::beast::http::buffer_body, boost::beast::http::basic_fields<std::allocator<char> > >, boost::beast::basic_stream<boost::asio::ip::tcp, boost::asio::any_io_executor, boost::beast::unlimited_rate_policy>, false, boost::beast::http::buffer_body, boost::beast::http::basic_fields<std::allocator<char> > > >, boost::system::error_code, unsigned long> >(boost::asio::detail::binder2<boost::beast::basic_stream<boost::asio::ip::tcp, boost::asio::any_io_executor, boost::beast::unlimited_rate_policy>::ops::transfer_op<false, boost::beast::detail::buffers_ref<boost::beast::buffers_prefix_view<boost::beast::buffers_suffix<boost::beast::buffers_cat_view<boost::beast::http::detail::chunk_size, boost::asio::const_buffer, boost::beast::http::chunk_crlf, boost::asio::const_buffer, boost::beast::http::chunk_crlf> > const&> >, boost::beast::http::detail::write_some_op<boost::beast::http::detail::write_op<(anonymous namespace)::incremental_read::stream_bytes_to_client()::{lambda()#1}::operator()()::{lambda(auto:1 const&, unsigned long)#1}, boost::beast::basic_stream<boost::asio::ip::tcp, boost::asio::any_io_executor, boost::beast::unlimited_rate_policy>, boost::beast::http::detail::serializer_is_done, false, boost::beast::http::buffer_body, boost::beast::http::basic_fields<std::allocator<char> > >, boost::beast::basic_stream<boost::asio::ip::tcp, boost::asio::any_io_executor, boost::beast::unlimited_rate_policy>, false, boost::beast::http::buffer_body, boost::beast::http::basic_fields<std::allocator<char> > > >, boost::system::error_code, unsigned long>&, boost::asio::detail::binder2<boost::beast::basic_stream<boost::asio::ip::tcp, boost::asio::any_io_executor, boost::beast::unlimited_rate_policy>::ops::transfer_op<false, boost::beast::detail::buffers_ref<boost::beast::buffers_prefix_view<boost::beast::buffers_suffix<boost::beast::buffers_cat_view<boost::beast::http::detail::chunk_size, boost::asio::const_buffer, boost::beast::http::chunk_crlf, boost::asio::const_buffer, boost::beast::http::chunk_crlf> > const&> >, boost::beast::http::detail::write_some_op<boost::beast::http::detail::write_op<(anonymous namespace)::incremental_read::stream_bytes_to_client()::{lambda()#1}::operator()()::{lambda(auto:1 const&, unsigned long)#1}, boost::beast::basic_stream<boost::asio::ip::tcp, boost::asio::any_io_executor, boost::beast::unlimited_rate_policy>, boost::beast::http::detail::serializer_is_done, false, boost::beast::http::buffer_body, boost::beast::http::basic_fields<std::allocator<char> > >, boost::beast::basic_stream<boost::asio::ip::tcp, boost::asio::any_io_executor, boost::beast::unlimited_rate_policy>, false, boost::beast::http::buffer_body, boost::beast::http::basic_fields<std::allocator<char> > > >, boost::system::error_code, unsigned long>&) (function=..., context=...)
    at /opt/irods-externals/boost1.81.0-2/include/boost/asio/detail/handler_invoke_helpers.hpp:51
#11 0x0000555556086937 in boost::asio::detail::executor_function::complete<boost::asio::detail::binder2<boost::beast::basic_stream<boost::asio::ip::tcp, boost::asio::any_io_executor, boost::beast::unlimited_rate_policy>::ops::transfer_op<false, boost::beast::detail::buffers_ref<boost::beast::buffers_prefix_view<boost::beast::buffers_suffix<boost::beast::buffers_cat_view<boost::beast::http::detail::chunk_size, boost::asio::const_buffer, boost::beast::http::chunk_crlf, boost::asio::const_buffer, boost::beast::http::chunk_crlf> > const&> >, boost::beast::http::detail::write_some_op<boost::beast::http::detail::write_op<(anonymous namespace)::incremental_read::stream_bytes_to_client()::{lambda()#1}::operator()()::{lambda(auto:1 const&, unsigned long)#1}, boost::beast::basic_stream<boost::asio::ip::tcp, boost::asio::any_io_executor, boost::beast::unlimited_rate_policy>, boost::beast::http::detail::serializer_is_done, false, boost::beast::http::buffer_body, boost::beast::http::basic_fields<std::allocator<char> > >, boost::beast::basic_stream<boost::asio::ip::tcp, boost::asio::any_io_executor, boost::beast::unlimited_rate_policy>, false, boost::beast::http::buffer_body, boost::beast::http::basic_fields<std::allocator<char> > > >, boost::system::error_code, unsigned long>, std::allocator<void> >(boost::asio::detail::executor_function::impl_base*, bool) (base=0x7fffdc002b70, call=true) at /opt/irods-externals/boost1.81.0-2/include/boost/asio/detail/executor_function.hpp:116
#12 0x0000555555dfa682 in boost::asio::detail::executor_function::operator() (this=0x7fffffffc860) at /opt/irods-externals/boost1.81.0-2/include/boost/asio/detail/executor_function.hpp:64
#13 0x0000555555dfa079 in boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::executor_function, boost::asio::detail::executor_function> (function=..., context=...) at /opt/irods-externals/boost1.81.0-2/include/boost/asio/detail/handler_invoke_helpers.hpp:51
#14 0x0000555555dfa77e in boost::asio::detail::executor_op<boost::asio::detail::executor_function, std::allocator<void>, boost::asio::detail::scheduler_operation>::do_complete (owner=0x7fffbc001550, base=0x7fffb4000eb0) at /opt/irods-externals/boost1.81.0-2/include/boost/asio/detail/executor_op.hpp:70
#15 0x0000555555de950e in boost::asio::detail::scheduler_operation::complete (this=0x7fffb4000eb0, owner=0x7fffbc001550, ec=..., bytes_transferred=0) at /opt/irods-externals/boost1.81.0-2/include/boost/asio/detail/scheduler_operation.hpp:40
#16 0x0000555555dfabbd in boost::asio::detail::strand_executor_service::run_ready_handlers (impl=std::shared_ptr<boost::asio::detail::strand_executor_service::strand_impl> (use count 5, weak count 0) = {...}) at /opt/irods-externals/boost1.81.0-2/include/boost/asio/detail/impl/strand_executor_service.ipp:150
#17 0x0000555555dfe409 in boost::asio::detail::strand_executor_service::invoker<boost::asio::io_context::basic_executor_type<std::allocator<void>, 4ul> const, void>::operator() (this=0x7fffffffc9c0) at /opt/irods-externals/boost1.81.0-2/include/boost/asio/detail/impl/strand_executor_service.hpp:136
#18 0x0000555555dfe2d9 in boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::strand_executor_service::invoker<boost::asio::io_context::basic_executor_type<std::allocator<void>, 4ul> const, void>, boost::asio::detail::strand_executor_service::invoker<boost::asio::io_context::basic_executor_type<std::allocator<void>, 4ul> const, void> > (function=..., context=...)
    at /opt/irods-externals/boost1.81.0-2/include/boost/asio/detail/handler_invoke_helpers.hpp:51
#19 0x0000555555dfe913 in boost::asio::detail::executor_op<boost::asio::detail::strand_executor_service::invoker<boost::asio::io_context::basic_executor_type<std::allocator<void>, 4ul> const, void>, boost::asio::detail::recycling_allocator<void, boost::asio::detail::thread_info_base::default_tag>, boost::asio::detail::scheduler_operation>::do_complete (owner=0x55555656d060, 
    base=0x5555564cdff0) at /opt/irods-externals/boost1.81.0-2/include/boost/asio/detail/executor_op.hpp:70
#20 0x0000555555de950e in boost::asio::detail::scheduler_operation::complete (this=0x5555564cdff0, owner=0x55555656d060, ec=..., bytes_transferred=0) at /opt/irods-externals/boost1.81.0-2/include/boost/asio/detail/scheduler_operation.hpp:40
#21 0x0000555555de90b7 in boost::asio::detail::scheduler::do_run_one (this=0x55555656d060, lock=..., this_thread=..., ec=...) at /opt/irods-externals/boost1.81.0-2/include/boost/asio/detail/impl/scheduler.ipp:492
#22 0x0000555555de8bf7 in boost::asio::detail::scheduler::run (this=0x55555656d060, ec=...) at /opt/irods-externals/boost1.81.0-2/include/boost/asio/detail/impl/scheduler.ipp:210
#23 0x0000555555ddfd2e in boost::asio::io_context::run (this=0x7fffffffd308) at /opt/irods-externals/boost1.81.0-2/include/boost/asio/impl/io_context.ipp:63
#24 0x0000555555dd8fb9 in main (_argc=2, _argv=0x7fffffffde68) at /mnt/hdd_3tb/github/irods_client_http_api/core/src/main.cpp:1112
```

**Comment by trel** [comment]
so, we should check it first?  or just catch this particular bad pattern more gracefully?

**Comment by korydraughn** [comment]
I have a PR on the way which caches the value upon connecting. From that point on, the session always returns the cached IP address or a placeholder if unavailable.

**Comment by trel** [comment]
ah, very good.
